export const ADD_MARKET_ITEM = 'ADD_MARKET_ITEM';

export const CLEAR_MARKET_ITEM_FIELDS = 'CLEAR_MARKET_ITEM_FIELDS';
export const CHANGE_MARKET_ITEM_FIELD = 'CHANGE_MARKET_ITEM_FIELD';
export const CHANGE_MARKET_ITEM_SALE_TYPE = 'CHANGE_MARKET_ITEM_SALE_TYPE';
