export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';

export const GET_EDITED_SERVICE_ID = 'GET_EDITED_SERVICE_ID';
export const CLEAR_EDITED_SERVICE_ID = 'CLEAR_EDITED_SERVICE_ID';
export const SAVE_EDITED_SERVICE = 'SAVE_EDITED_SERVICE';

export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const CLEAR_SERVICE_FIELD = 'CLEAR_SERVICE_FIELD';